[build]
  base = "motionify-app"
  command = "npm ci && npm run build"
  publish = "motionify-app/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js App Router handles /v2 route automatically


